<?php

return [
    'enabled' => env('INTELLIGENCE_ENABLED', true),
    'path' => storage_path('app/private/intelligence'),
    'queue' => env('INTELLIGENCE_QUEUE', 'intelligence'),
    'schema' => 'core',
    'horizon' => 12,
    'lookback' => 20,
    'minimum_move_bps' => 10.0,
    'extreme_fraction' => 0.2,
    'max_rows' => 3000,
    'max_seconds' => 480,
    'max_model_age_days' => 14,
    'max_signal_age_periods' => 2,
    'knn' => [
        'train_size' => 250,
        'test_size' => 100,
        'gap' => 0,
        'k_cap' => 65,
        'max_distance' => 0.25,
        'min_effective_neighbors' => 3.0,
        'min_confidence' => 0.6,
        'min_validation_rows' => 50,
        'min_directional_predictions' => 5,
        'min_semantic_precision' => 0.55,
        'max_contradiction_rate' => 0.05,
        'min_coverage' => 0.01,
    ],
    'patterns' => [
        'enabled' => true,
        'as_knn_features' => true,
        'min_samples' => 100,
        'min_block_rows' => 15,
        'trees' => 50,
        'k' => 9,
    ],
];
